-- AlterTable
ALTER TABLE "public"."Quiz" ADD COLUMN     "academicYear" TEXT NOT NULL DEFAULT '2023-2024',
ADD COLUMN     "subterm" TEXT NOT NULL DEFAULT 'MIDTERM',
ADD COLUMN     "term" TEXT NOT NULL DEFAULT 'AUTUMN';
